# Generated by Django 3.1.7 on 2021-03-02 08:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='offer_name')),
                ('discounted_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('orignal_price', models.FloatField(default=0.0)),
                ('image_url', models.ImageField(upload_to='')),
                ('valid_from', models.DateTimeField()),
                ('valid_till', models.DateTimeField()),
                ('approval_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 3, 2, 13, 49, 35, 1035))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 3, 2, 13, 49, 35, 1035))),
                ('restaurant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='feed.restaurant')),
            ],
        ),
    ]
