# Generated by Django 3.1.7 on 2021-04-11 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='')),
                ('reveiw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.review', verbose_name='reveiew_id')),
            ],
        ),
    ]
