# Generated by Django 3.1.7 on 2021-03-02 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 14, 35, 32, 760079)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 14, 35, 32, 760079)),
        ),
    ]
