# Generated by Django 3.1.7 on 2021-04-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_review_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewimage',
            old_name='reveiw',
            new_name='review',
        ),
    ]
