# Generated by Django 3.1.7 on 2021-03-09 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20210308_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 16, 32, 30, 471276)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 16, 32, 30, 471276)),
        ),
    ]
