# Generated by Django 3.1.7 on 2021-04-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20210411_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menu_image',
        ),
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('sort_order', models.SmallIntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.restaurant', verbose_name='reveiew_id')),
            ],
        ),
    ]
