# Generated by Django 3.1.7 on 2021-03-02 17:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20210302_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='coupon',
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='feed.offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 22, 47, 0, 559850)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 22, 47, 0, 559850)),
        ),
    ]
