# Generated by Django 3.1.7 on 2021-04-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20210411_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feed.restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuimage',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.restaurant'),
        ),
    ]
