# Generated by Django 3.1.7 on 2021-03-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20210309_1632'),
        ('feed', '0003_review_image'),
    ]

    operations = [
    ]
