# Generated by Django 3.1.7 on 2021-04-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20210411_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.restaurant'),
        ),
    ]
