# Generated by Django 3.1.7 on 2021-03-02 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20210302_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 0, 12, 17, 625243)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 0, 12, 17, 625243)),
        ),
    ]
