# Generated by Django 3.1.7 on 2021-05-08 15:07

from django.db import migrations, models
import django.db.models.deletion
import project.feed.models.menu_image
import project.feed.models.offer
import project.feed.models.restaurant
import project.feed.models.reveiw_images
import project.feed.models.user_profile


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20210411_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuimage',
            name='image',
            field=models.ImageField(upload_to=project.feed.models.menu_image.image_upload_path),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image_url',
            field=models.ImageField(upload_to=project.feed.models.offer.offer_image_path),
        ),
        migrations.AlterField(
            model_name='offer',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.restaurant'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=project.feed.models.user_profile.image_upload_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=project.feed.models.restaurant.cover_upload_path, verbose_name='restaurant_cover_image'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, upload_to=project.feed.models.restaurant.image_upload_path, verbose_name='restaurant_image'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo_image',
            field=models.ImageField(blank=True, upload_to=project.feed.models.restaurant.logo_upload_path, verbose_name='restaurant_logo_image'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image_url',
            field=models.ImageField(upload_to=project.feed.models.reveiw_images.review_image_path),
        ),
    ]
