# Generated by Django 3.1.7 on 2021-04-23 00:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0007_auto_20210418_1145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useroffers',
            unique_together={('user', 'offer')},
        ),
    ]
