# Generated by Django 3.1.7 on 2021-05-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20210423_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating_overall',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
