# Generated by Django 3.1.7 on 2021-05-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_offer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('DINE IN ONLY', 'Dine In Only'), ('DINE IN & TAKE AWAY', 'Dine In & Take Away'), ('DINE IN & DELIVERY', 'Dine In & Delivery'), ('TAKE AWAY ONLY', 'Take Away Only'), ('TAKE AWAY & DELIVERY', 'Take Away & Delivery'), ('DELIVERY ONLY', 'Delivery Only'), ('DINE IN & TAKE AWAY & DELIVERY', 'Dine In & Take Away & Delivery')], default='DINE IN & TAKE AWAY & DELIVERY', max_length=50),
        ),
    ]
