# Generated by Django 3.1.7 on 2021-05-11 16:13

from django.db import migrations, models
import project.feed.models.menu_image
import project.feed.models.offer
import project.feed.models.restaurant
import project.feed.models.reveiw_images
import project.feed.models.user_profile


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_offer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('DINE IN ONLY', 'Dine In Only'), ('DINE IN & TAKE AWAY', 'Dine In & Take Away'), ('DINE IN & DELIVERY', 'Dine In & Delivery'), ('TAKE AWAY ONLY', 'Take Away Only'), ('TAKE AWAY & DELIVERY', 'Take Away & Delivery'), ('DELIVERY ONLY', 'Delivery Only'), ('DINE IN & TAKE AWAY & DELIVERY', 'Dine In & Take Away & Delivery')], default='DINE IN & TAKE AWAY & DELIVERY', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuimage',
            name='image',
            field=models.ImageField(upload_to=project.feed.models.menu_image.image_upload_path),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image_url',
            field=models.ImageField(upload_to=project.feed.models.offer.offer_image_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=project.feed.models.user_profile.image_upload_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=project.feed.models.restaurant.cover_upload_path, verbose_name='restaurant_cover_image'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, upload_to=project.feed.models.restaurant.image_upload_path, verbose_name='restaurant_image'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo_image',
            field=models.ImageField(blank=True, upload_to=project.feed.models.restaurant.logo_upload_path, verbose_name='restaurant_logo_image'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image_url',
            field=models.ImageField(upload_to=project.feed.models.reveiw_images.review_image_path),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
